steps:
  - name: 'gcr.io/cloud-builders/docker:latest'
    args: ['build',
           '-t',
           'europe-west1-docker.pkg.dev/$PROJECT_ID/phenix/operators/spark-operator:${BRANCH_NAME}-${BUILD_ID}',
           '.']
images: [
  'europe-west1-docker.pkg.dev/$PROJECT_ID/phenix/operators/spark-operator:${BRANCH_NAME}-${BUILD_ID}'
]

timeout: 1800s
